apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: vm-composition
spec:
  compositeTypeRef:
    apiVersion: my-a1-demo-task-app.com/v1alpha1
    kind: CompositeVirtualMachine
  resources:
    - name: virtualMachine
      base:
        apiVersion: compute.azure.crossplane.io/v1alpha3
        kind: VirtualMachine
        spec:
          resourceGroupName: my-resource-group
          location: West Europe
          providerConfigRef:
            name: azure-provider
          hardwareProfile:
            vmSize: Standard_B1ms
          osProfile:
            computerName: my-vm
            adminUsername: azureuser
            adminPassword: ${VM_ADMIN_PASSWORD}
          storageProfile:
            osDisk:
              createOption: FromImage
              name: my-osdisk
              managedDiskType: Standard_LRS
          networkProfile:
            networkInterfaces:
              - subnetName: my-subnet
                virtualNetworkName: my-vnet
                resourceGroupName: my-resource-group
